#!/bin/bash
# set -x
set -euo pipefail

echo "$1" | sudo tee /proc/sys/kernel/yama/ptrace_scope 1>/dev/null
sudo sed -ie "s/kernel.yama.ptrace_scope.*/kernel.yama.ptrace_scope = $1/" /etc/sysctl.d/10-ptrace.conf

echo "ptrace_scope permanently set to $(cat /proc/sys/kernel/yama/ptrace_scope)"
